### ISSUE TITLE
Global name `start_dir` is not defined

### ISSUE THREAD

**Issue by sirnacnud** [beeftornado/duplicate-image-finder#4]
I installed the package with `pip install -e .` and now when trying to run it, I get the below error.

```
$ app -d ios/
Traceback (most recent call last):
  File "/usr/local/bin/app", line 11, in <module>
    load_entry_point('DuplicateImageFinder', 'console_scripts', 'app')()
  File "/Users/dcunningham/Source/duplicate-image-finder/duplicateimagefinder/app.py", line 139, in main
    for d in (start_dir, compare_to):
NameError: global name 'start_dir' is not defined
```

**Comment by beeftornado** [comment]
Fixed in https://github.com/beeftornado/duplicate-image-finder/commit/7a7f84e80d66f91197d2b5f04c2e087e663c7fd2

I just added install instructions that I verified from scratch just now.

**Comment by sirnacnud** [comment]
Looking at the code, the problem seems to be that you can't modify the dictionary returned by locals().

https://stackoverflow.com/questions/21826934/locals-updatekwargs-is-not-working
